### ISSUE TITLE
No packagist?

### ISSUE THREAD

**Issue by attozk** [dobryak/phpsyslognet#1]
Just the package I was looking for!

However it doesn't exist on https://packagist.org/?query=phpsyslognet. Would love to see it getting submitted.

Thanks

**Comment by dobryak** [comment]
Hello,

Sure, I will add it to packagist in my spare time.

**Comment by dobryak** [comment]
Ok, it is done:
https://packagist.org/packages/dobryak/phpsyslognet

**Comment by attozk** [comment]
🎉
